/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BhTemp {
    }
}
declare global {
    interface HTMLBhTempElement extends Components.BhTemp, HTMLStencilElement {
    }
    var HTMLBhTempElement: {
        prototype: HTMLBhTempElement;
        new (): HTMLBhTempElement;
    };
    interface HTMLElementTagNameMap {
        "bh-temp": HTMLBhTempElement;
    }
}
declare namespace LocalJSX {
    interface BhTemp {
    }
    interface IntrinsicElements {
        "bh-temp": BhTemp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bh-temp": LocalJSX.BhTemp & JSXBase.HTMLAttributes<HTMLBhTempElement>;
        }
    }
}
