/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Connection, Query, SearchResult, Template, Theme } from "@webpress/core";
import { AdMapping } from "./components/model/AdMapping";
export namespace Components {
    interface BhImports {
    }
    interface BhPopularPosts {
        "global": Connection.Context;
        "size": number;
    }
    interface BhSearchForm {
        "focused": boolean;
        "term": string;
    }
    interface BhSearchPagination {
        "pagination": Query.Pagination<SearchResult>;
    }
    interface BhSearchResultOccurances {
        "result": SearchResult;
        "searchQuery": String;
    }
    interface BhSearchResultTitle {
        "result": SearchResult;
        "searchQuery": String;
    }
    interface BhSearchResults {
        "connection": Connection;
    }
    interface BhSearchResultsPage {
        "global": Connection.Context;
    }
    interface BstAdSlot {
        "adUnitPath": string;
        "sizeMap": AdMapping;
        "slotRenderEnded": (
    event: googletag.events.SlotRenderEndedEvent
  ) => any;
    }
    interface ExaMenuButton {
        "active": boolean;
    }
    interface ExaNameplateMenus {
        "global": Connection.Context;
        "query": Template.Query;
        "searchQuery": string;
        "theme": Theme;
    }
    interface HrldArticleSidebar {
    }
    interface HrldHomepageLeaderboard {
    }
    interface HrldHomepageSidekick {
    }
    interface HrldPreflight {
    }
    interface HrldTallAd {
    }
}
declare global {
    interface HTMLBhImportsElement extends Components.BhImports, HTMLStencilElement {
    }
    var HTMLBhImportsElement: {
        prototype: HTMLBhImportsElement;
        new (): HTMLBhImportsElement;
    };
    interface HTMLBhPopularPostsElement extends Components.BhPopularPosts, HTMLStencilElement {
    }
    var HTMLBhPopularPostsElement: {
        prototype: HTMLBhPopularPostsElement;
        new (): HTMLBhPopularPostsElement;
    };
    interface HTMLBhSearchFormElement extends Components.BhSearchForm, HTMLStencilElement {
    }
    var HTMLBhSearchFormElement: {
        prototype: HTMLBhSearchFormElement;
        new (): HTMLBhSearchFormElement;
    };
    interface HTMLBhSearchPaginationElement extends Components.BhSearchPagination, HTMLStencilElement {
    }
    var HTMLBhSearchPaginationElement: {
        prototype: HTMLBhSearchPaginationElement;
        new (): HTMLBhSearchPaginationElement;
    };
    interface HTMLBhSearchResultOccurancesElement extends Components.BhSearchResultOccurances, HTMLStencilElement {
    }
    var HTMLBhSearchResultOccurancesElement: {
        prototype: HTMLBhSearchResultOccurancesElement;
        new (): HTMLBhSearchResultOccurancesElement;
    };
    interface HTMLBhSearchResultTitleElement extends Components.BhSearchResultTitle, HTMLStencilElement {
    }
    var HTMLBhSearchResultTitleElement: {
        prototype: HTMLBhSearchResultTitleElement;
        new (): HTMLBhSearchResultTitleElement;
    };
    interface HTMLBhSearchResultsElement extends Components.BhSearchResults, HTMLStencilElement {
    }
    var HTMLBhSearchResultsElement: {
        prototype: HTMLBhSearchResultsElement;
        new (): HTMLBhSearchResultsElement;
    };
    interface HTMLBhSearchResultsPageElement extends Components.BhSearchResultsPage, HTMLStencilElement {
    }
    var HTMLBhSearchResultsPageElement: {
        prototype: HTMLBhSearchResultsPageElement;
        new (): HTMLBhSearchResultsPageElement;
    };
    interface HTMLBstAdSlotElement extends Components.BstAdSlot, HTMLStencilElement {
    }
    var HTMLBstAdSlotElement: {
        prototype: HTMLBstAdSlotElement;
        new (): HTMLBstAdSlotElement;
    };
    interface HTMLExaMenuButtonElement extends Components.ExaMenuButton, HTMLStencilElement {
    }
    var HTMLExaMenuButtonElement: {
        prototype: HTMLExaMenuButtonElement;
        new (): HTMLExaMenuButtonElement;
    };
    interface HTMLExaNameplateMenusElement extends Components.ExaNameplateMenus, HTMLStencilElement {
    }
    var HTMLExaNameplateMenusElement: {
        prototype: HTMLExaNameplateMenusElement;
        new (): HTMLExaNameplateMenusElement;
    };
    interface HTMLHrldArticleSidebarElement extends Components.HrldArticleSidebar, HTMLStencilElement {
    }
    var HTMLHrldArticleSidebarElement: {
        prototype: HTMLHrldArticleSidebarElement;
        new (): HTMLHrldArticleSidebarElement;
    };
    interface HTMLHrldHomepageLeaderboardElement extends Components.HrldHomepageLeaderboard, HTMLStencilElement {
    }
    var HTMLHrldHomepageLeaderboardElement: {
        prototype: HTMLHrldHomepageLeaderboardElement;
        new (): HTMLHrldHomepageLeaderboardElement;
    };
    interface HTMLHrldHomepageSidekickElement extends Components.HrldHomepageSidekick, HTMLStencilElement {
    }
    var HTMLHrldHomepageSidekickElement: {
        prototype: HTMLHrldHomepageSidekickElement;
        new (): HTMLHrldHomepageSidekickElement;
    };
    interface HTMLHrldPreflightElement extends Components.HrldPreflight, HTMLStencilElement {
    }
    var HTMLHrldPreflightElement: {
        prototype: HTMLHrldPreflightElement;
        new (): HTMLHrldPreflightElement;
    };
    interface HTMLHrldTallAdElement extends Components.HrldTallAd, HTMLStencilElement {
    }
    var HTMLHrldTallAdElement: {
        prototype: HTMLHrldTallAdElement;
        new (): HTMLHrldTallAdElement;
    };
    interface HTMLElementTagNameMap {
        "bh-imports": HTMLBhImportsElement;
        "bh-popular-posts": HTMLBhPopularPostsElement;
        "bh-search-form": HTMLBhSearchFormElement;
        "bh-search-pagination": HTMLBhSearchPaginationElement;
        "bh-search-result-occurances": HTMLBhSearchResultOccurancesElement;
        "bh-search-result-title": HTMLBhSearchResultTitleElement;
        "bh-search-results": HTMLBhSearchResultsElement;
        "bh-search-results-page": HTMLBhSearchResultsPageElement;
        "bst-ad-slot": HTMLBstAdSlotElement;
        "exa-menu-button": HTMLExaMenuButtonElement;
        "exa-nameplate-menus": HTMLExaNameplateMenusElement;
        "hrld-article-sidebar": HTMLHrldArticleSidebarElement;
        "hrld-homepage-leaderboard": HTMLHrldHomepageLeaderboardElement;
        "hrld-homepage-sidekick": HTMLHrldHomepageSidekickElement;
        "hrld-preflight": HTMLHrldPreflightElement;
        "hrld-tall-ad": HTMLHrldTallAdElement;
    }
}
declare namespace LocalJSX {
    interface BhImports {
    }
    interface BhPopularPosts {
        "global"?: Connection.Context;
        "size"?: number;
    }
    interface BhSearchForm {
        "focused"?: boolean;
        "term"?: string;
    }
    interface BhSearchPagination {
        "pagination"?: Query.Pagination<SearchResult>;
    }
    interface BhSearchResultOccurances {
        "result"?: SearchResult;
        "searchQuery"?: String;
    }
    interface BhSearchResultTitle {
        "result"?: SearchResult;
        "searchQuery"?: String;
    }
    interface BhSearchResults {
        "connection"?: Connection;
    }
    interface BhSearchResultsPage {
        "global"?: Connection.Context;
    }
    interface BstAdSlot {
        "adUnitPath": string;
        "sizeMap": AdMapping;
        "slotRenderEnded"?: (
    event: googletag.events.SlotRenderEndedEvent
  ) => any;
    }
    interface ExaMenuButton {
        "active"?: boolean;
    }
    interface ExaNameplateMenus {
        "global"?: Connection.Context;
        "query"?: Template.Query;
        "searchQuery"?: string;
        "theme"?: Theme;
    }
    interface HrldArticleSidebar {
    }
    interface HrldHomepageLeaderboard {
    }
    interface HrldHomepageSidekick {
    }
    interface HrldPreflight {
    }
    interface HrldTallAd {
    }
    interface IntrinsicElements {
        "bh-imports": BhImports;
        "bh-popular-posts": BhPopularPosts;
        "bh-search-form": BhSearchForm;
        "bh-search-pagination": BhSearchPagination;
        "bh-search-result-occurances": BhSearchResultOccurances;
        "bh-search-result-title": BhSearchResultTitle;
        "bh-search-results": BhSearchResults;
        "bh-search-results-page": BhSearchResultsPage;
        "bst-ad-slot": BstAdSlot;
        "exa-menu-button": ExaMenuButton;
        "exa-nameplate-menus": ExaNameplateMenus;
        "hrld-article-sidebar": HrldArticleSidebar;
        "hrld-homepage-leaderboard": HrldHomepageLeaderboard;
        "hrld-homepage-sidekick": HrldHomepageSidekick;
        "hrld-preflight": HrldPreflight;
        "hrld-tall-ad": HrldTallAd;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bh-imports": LocalJSX.BhImports & JSXBase.HTMLAttributes<HTMLBhImportsElement>;
            "bh-popular-posts": LocalJSX.BhPopularPosts & JSXBase.HTMLAttributes<HTMLBhPopularPostsElement>;
            "bh-search-form": LocalJSX.BhSearchForm & JSXBase.HTMLAttributes<HTMLBhSearchFormElement>;
            "bh-search-pagination": LocalJSX.BhSearchPagination & JSXBase.HTMLAttributes<HTMLBhSearchPaginationElement>;
            "bh-search-result-occurances": LocalJSX.BhSearchResultOccurances & JSXBase.HTMLAttributes<HTMLBhSearchResultOccurancesElement>;
            "bh-search-result-title": LocalJSX.BhSearchResultTitle & JSXBase.HTMLAttributes<HTMLBhSearchResultTitleElement>;
            "bh-search-results": LocalJSX.BhSearchResults & JSXBase.HTMLAttributes<HTMLBhSearchResultsElement>;
            "bh-search-results-page": LocalJSX.BhSearchResultsPage & JSXBase.HTMLAttributes<HTMLBhSearchResultsPageElement>;
            "bst-ad-slot": LocalJSX.BstAdSlot & JSXBase.HTMLAttributes<HTMLBstAdSlotElement>;
            "exa-menu-button": LocalJSX.ExaMenuButton & JSXBase.HTMLAttributes<HTMLExaMenuButtonElement>;
            "exa-nameplate-menus": LocalJSX.ExaNameplateMenus & JSXBase.HTMLAttributes<HTMLExaNameplateMenusElement>;
            "hrld-article-sidebar": LocalJSX.HrldArticleSidebar & JSXBase.HTMLAttributes<HTMLHrldArticleSidebarElement>;
            "hrld-homepage-leaderboard": LocalJSX.HrldHomepageLeaderboard & JSXBase.HTMLAttributes<HTMLHrldHomepageLeaderboardElement>;
            "hrld-homepage-sidekick": LocalJSX.HrldHomepageSidekick & JSXBase.HTMLAttributes<HTMLHrldHomepageSidekickElement>;
            "hrld-preflight": LocalJSX.HrldPreflight & JSXBase.HTMLAttributes<HTMLHrldPreflightElement>;
            "hrld-tall-ad": LocalJSX.HrldTallAd & JSXBase.HTMLAttributes<HTMLHrldTallAdElement>;
        }
    }
}
